<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['incoming_firewall_allowed_incoming_connections'] = 'Разрешенные входящие подключения';
$lang['incoming_firewall_app_description'] = 'Приложение "Брандмауэр" не пускает плохих парней, ограничивая доступ к вашей системе и блокирует нежелательные соединения.';
$lang['incoming_firewall_app_name'] = 'Брандмауэр';
$lang['incoming_firewall_blocked_incoming_connections'] = 'Заблокированные входящие подключения';
