#!/usr/clearos/sandbox/usr/bin/php
<?php

/**
 * Remove all Incoming Firewall rules.
 *
 * @category   apps
 * @package    incoming_firewall
 * @subpackage scripts
 * @author     ClearFoundation <developer@clearfoundation.com>
 * @copyright  2015 ClearFoundation
 * @license    http://www.gnu.org/copyleft/gpl.html GNU General Public License version 3 or later
 * @link       http://www.clearfoundation.com/docs/developer/apps/incoming_firewall/
 */

///////////////////////////////////////////////////////////////////////////////
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// N A M E S P A C E
///////////////////////////////////////////////////////////////////////////////

namespace clearos\apps\incoming_firewall;

///////////////////////////////////////////////////////////////////////////////
// B O O T S T R A P
///////////////////////////////////////////////////////////////////////////////

$bootstrap = getenv('CLEAROS_BOOTSTRAP') ? getenv('CLEAROS_BOOTSTRAP') : '/usr/clearos/framework/shared';
require_once $bootstrap . '/bootstrap.php';

///////////////////////////////////////////////////////////////////////////////
// T R A N S L A T I O N S
///////////////////////////////////////////////////////////////////////////////

clearos_load_language('incoming_firewall');

///////////////////////////////////////////////////////////////////////////////
// D E P E N D E N C I E S
///////////////////////////////////////////////////////////////////////////////

// Classes
//--------

use \clearos\apps\incoming_firewall\Incoming as Incoming;

clearos_load_library('incoming_firewall/Incoming');

// Exceptions
//-----------

use \Exception as Exception;

///////////////////////////////////////////////////////////////////////////////
// M A I N
///////////////////////////////////////////////////////////////////////////////

$incoming = new Incoming();

try {

    $rules = $incoming->get_allow_ports();
    foreach ($rules as $rule)
        $incoming->delete_allow_port($rule['protocol_name'], $rule['port']);

    $rules = $incoming->get_allow_port_ranges();
    foreach ($rules as $rule)
        $incoming->delete_allow_port_range($rule['protocol_name'], $rule['from'], $rule['to']);

    $rules = $incoming->get_block_hosts();
    foreach ($rules as $rule)
        $incoming->delete_block_host($rule['host']);
} catch (Exception $e) {
    echo clearos_exception_message($e) . "\n";
    clearos_log('incoming_firewall', clearos_exception_message($e));
}

// vim: syntax=php ts=4
