<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['incoming_firewall_allowed_incoming_connections'] = 'Tillåt inkommande anslutningar';
$lang['incoming_firewall_app_description'] = 'Den inkommande brandväggen håller de stygga pojkarna utanför genom att begränsa åtkomsten till ditt system och blockera oönskade anslutningar.';
$lang['incoming_firewall_app_name'] = 'Inkommande brandvägg';
$lang['incoming_firewall_blocked_incoming_connections'] = 'Blockerade inkommande anslutningar';
