<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['incoming_firewall_allowed_incoming_connections'] = 'Zezwolone połączenia przychodzące';
$lang['incoming_firewall_app_description'] = 'Aplikacja Firewall wejścia trzyma "złych gości" z dala, ograniczając dostęp do Twojego systemu oraz blokując niechciane połączenia.';
$lang['incoming_firewall_app_name'] = 'Firewall wejścia';
$lang['incoming_firewall_blocked_incoming_connections'] = 'Zablokowane połączenia przychodzące';
