<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['incoming_firewall_allowed_incoming_connections'] = 'Allowed Incoming Connections';
$lang['incoming_firewall_app_description'] = 'The Incoming Firewall app keeps the bad guys out by limiting access to your system and blocking unwanted connections.';
$lang['incoming_firewall_app_name'] = 'Incoming Firewall';
$lang['incoming_firewall_blocked_incoming_connections'] = 'Blocked Incoming Connections';
